version: '3.1'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: '123456'
      POSTGRES_USER: postgres
      POSTGRES_DB: hayot-db
    expose:
      - "5433"
    ports:
      - "5433"
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080